<a href="https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="在 Colab 中打开"/></a> 

[查看源码](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb) | [查看幻灯片](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/slides/00_pytorch_and_deep_learning_fundamentals.pdf) | [观看视频讲解](https://youtu.be/Z_ikDlimN6A?t=76) 

# 00. PyTorch 基础

## 什么是 PyTorch？

[PyTorch](https://pytorch.org/) 是一个开源的机器学习与深度学习框架。

## PyTorch 可以用来做什么？

PyTorch 允许你使用 Python 代码对数据进行操作和处理，并编写机器学习算法。

## 谁在使用 PyTorch？

全球许多大型科技公司，例如 [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/)、Tesla 和 Microsoft，以及像 [OpenAI](https://openai.com/blog/openai-pytorch/) 这样的人工智能研究机构，都在使用 PyTorch 支撑研究并将机器学习应用到产品中。

![PyTorch 在工业与研究中的应用](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

例如，Andrej Karpathy（Tesla AI 负责人）做过多场演讲（[PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE)、[Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)），介绍 Tesla 如何使用 PyTorch 驱动其自动驾驶计算机视觉模型。

PyTorch 也被用于农业等行业，例如用于[为拖拉机上的计算机视觉提供能力](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1)。

## 为什么使用 PyTorch？

机器学习研究者非常喜欢 PyTorch。并且截至 2022 年 2 月，PyTorch 已是 [Papers With Code](https://paperswithcode.com/trends) 上使用最广泛的深度学习框架（该网站用于跟踪机器学习论文及其配套代码仓库）。

PyTorch 还会在幕后处理很多事情，例如 GPU 加速（让你的代码运行更快）。

所以你可以专注在数据处理和算法编写上，PyTorch 会帮助你高效运行。

如果像 Tesla 和 Meta（Facebook）这样的公司都用它来构建并部署模型，驱动数百个应用、上千辆汽车并服务数十亿人群，那它在开发与生产层面显然也足够强大。

## 本模块将覆盖什么

本课程被拆分为多个部分（notebook）。

每个 notebook 都会讲解 PyTorch 中的重要思想与概念。

后续 notebook 会建立在前一个 notebook 的知识之上（编号从 00、01、02 开始，持续递增）。

这个 notebook 聚焦于机器学习和深度学习最基础的构件：张量（tensor）。

具体来说，我们将覆盖：

| **主题** | **内容** |
| ----- | ----- |
| **张量简介** | 张量是所有机器学习与深度学习的基础构件。 |
| **创建张量** | 张量可以表示几乎任意类型的数据（图像、文本、数字表格）。 |
| **从张量中获取信息** | 既然可以把信息放进张量，也要会把信息取出来。 |
| **操作张量** | 机器学习算法（如神经网络）会以多种方式操作张量，例如加法、乘法、组合。 | 
| **处理张量形状** | 机器学习中最常见的问题之一是形状不匹配（把形状不兼容的张量混在一起）。 |
| **张量索引** | 如果你做过 Python 列表或 NumPy 数组索引，那么张量索引非常类似，只是张量维度可能更多。 |
| **混用 PyTorch 张量与 NumPy** | PyTorch 使用张量（[`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)），NumPy 使用数组（[`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)），有时你会想混合使用。 | 
| **可复现性** | 机器学习非常依赖实验与随机性，有时你会希望这种随机性可控。 |
| **在 GPU 上运行张量** | GPU（图形处理器）可以让代码更快，PyTorch 使在 GPU 上运行代码变得简单。 |

## 去哪里求助？

本课程所有材料都托管在 [GitHub](https://github.com/mrdbourke/pytorch-deep-learning)。

如果你遇到问题，也可以在那里的 [Discussions 页面](https://github.com/mrdbourke/pytorch-deep-learning/discussions)提问。

此外还有 [PyTorch 开发者论坛](https://discuss.pytorch.org/)，这是一个非常有帮助的 PyTorch 交流社区。

## 导入 PyTorch

 > **注意：** 运行本 notebook 中任何代码之前，你应该先完成 [PyTorch 环境配置步骤](https://pytorch.org/get-started/locally/)。
 >
 > 但是，**如果你在 Google Colab 上运行**，通常会直接可用（Google Colab 预装了 PyTorch 及其他常用库）。

我们先导入 PyTorch，并检查当前使用的版本。

In [1]:
import torch
torch.__version__

'1.13.1+cu116'

很好，看起来我们拿到了 PyTorch 1.10.0+。

这意味着你在学习这份材料时，与 PyTorch 1.10.0+ 的兼容性最佳；如果你的版本显著高于这个范围，可能会看到一些不一致。

如果你遇到问题，请在课程的 [GitHub Discussions 页面](https://github.com/mrdbourke/pytorch-deep-learning/discussions)发帖。

## 张量简介

现在我们已经导入了 PyTorch，接下来学习张量（tensor）。

张量是机器学习的基础构件。

它的职责是用数值方式表示数据。

例如，你可以把一张图像表示为形状为 `[3, 224, 224]` 的张量，这表示 `[colour_channels, height, width]`：图像有 `3` 个颜色通道（红、绿、蓝），高度 `224` 像素，宽度 `224` 像素。

![从输入图像到张量表示的示意图：图像被拆分为 3 个颜色通道以及表示高宽的数值](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

用张量的术语来说，这个张量有三个维度，分别对应 `colour_channels`、`height` 和 `width`。

不过我们先不着急。

让我们通过写代码来进一步理解张量。


### 创建张量

PyTorch 非常强调张量，甚至专门有一整页文档介绍 [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) 类。

你的第一个小作业是花 10 分钟[阅读 `torch.Tensor` 文档](https://pytorch.org/docs/stable/tensors.html)。当然可以稍后再做。

先来写代码。

我们要创建的第一个对象是 **scalar（标量）**。

标量是一个单独的数字，在张量语境里它是一个零维张量。

> **注意：** 这也是本课程的一个惯例。我们会专注于编写具体代码，但我也会经常布置阅读 PyTorch 文档的练习。因为课程结束后，你很可能还会继续深入学习，而文档会是你经常访问的地方。

In [ ]:
# 标量（Scalar）
scalar = torch.tensor(7)
scalar

tensor(7)

看到上面输出的 `tensor(7)` 了吗？

这说明虽然 `scalar` 是一个单独的数字，但它的类型是 `torch.Tensor`。

我们可以使用 `ndim` 属性检查张量的维度数。

In [3]:
scalar.ndim

0

如果我们想把张量里的数值取出来呢？

也就是把它从 `torch.Tensor` 变成 Python 整数？

可以使用 `item()` 方法。

In [ ]:
# 获取张量中的 Python 数值（仅适用于单元素张量）
scalar.item()

7

好，现在来看 **vector（向量）**。

向量是一个一维张量，但可以包含多个数字。

例如，你可以用向量 `[3, 2]` 表示房子的 `[bedrooms, bathrooms]`（卧室数、卫生间数）。也可以用 `[3, 2, 2]` 表示 `[bedrooms, bathrooms, car_parks]`（卧室数、卫生间数、车位数）。

这里的重要趋势是：向量在表示内容上非常灵活（张量同样如此）。

In [ ]:
# 向量（Vector）
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

很好，`vector` 现在包含两个 7，这是我最喜欢的数字。

你觉得它会有多少个维度？

In [ ]:
# 检查 vector 的维度数
vector.ndim

1

嗯，有点奇怪，`vector` 里有两个数字，但只有一个维度。

我告诉你一个小技巧。

在 PyTorch 里，你可以通过最外层方括号（`[`）的层数判断张量有多少维度，只需要数一侧即可。

`vector` 有几层方括号？

张量还有一个重要概念是 `shape` 属性。shape 告诉你其中元素是如何排列的。

我们来看一下 `vector` 的 shape。

In [ ]:
# 检查 vector 的 shape
vector.shape

torch.Size([2])

上面返回 `torch.Size([2])`，这表示我们的向量 shape 是 `[2]`。原因是我们在方括号中放了两个元素（`[7, 7]`）。

现在来看 **matrix（矩阵）**。

In [ ]:
# 矩阵（Matrix）
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

哇！更多数字！矩阵和向量一样灵活，只是它多了一个维度。



In [ ]:
# 检查维度数
MATRIX.ndim

2

`MATRIX` 有两个维度（你有数最外层一侧方括号的层数吗？）

你觉得它的 `shape` 会是什么？

In [10]:
MATRIX.shape

torch.Size([2, 2])

我们得到输出 `torch.Size([2, 2])`，因为 `MATRIX` 的深度为 2、宽度也为 2。

我们来创建一个 **tensor（张量）** 怎么样？

In [ ]:
# 张量（Tensor）
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

哇！这个张量看起来很不错。

我想强调：张量几乎可以表示任何东西。

我们刚创建的这个张量，甚至可以表示一家牛排和杏仁酱商店（这两样都是我最爱的食物）的销售数据。

![Google Sheets 中的一个简单张量示例：星期几、牛排销量和杏仁酱销量](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

你觉得它有多少个维度？（提示：使用方括号计数技巧）

In [ ]:
# 检查 TENSOR 的维度数
TENSOR.ndim

3

它的 shape 又是什么呢？

In [ ]:
# 检查 TENSOR 的 shape
TENSOR.shape

torch.Size([1, 3, 3])

好的，它输出 `torch.Size([1, 3, 3])`。

维度是从外向内看的。

这意味着有 1 个维度块，每个块是 3x3。

![不同张量维度示例](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **注意：** 你可能已经注意到，我对 `scalar` 和 `vector` 用小写，而对 `MATRIX` 和 `TENSOR` 用大写。这是有意为之。在实践中，标量和向量通常会用小写字母表示，例如 `y` 或 `a`；矩阵和张量通常会用大写字母表示，例如 `X` 或 `W`。
>
> 你还可能会看到 matrix 和 tensor 这两个词被交替使用，这很常见。因为在 PyTorch 中你经常处理的是 `torch.Tensor`（因此常叫 tensor），但它到底是标量、向量、矩阵还是更高维对象，取决于其内部 shape 与维度。

我们来总结一下。

| 名称 | 它是什么？ | 维度数 | 常见记号（小写/大写） |
| ----- | ----- | ----- | ----- |
| **scalar** | 单个数字 | 0 | 小写（`a`） | 
| **vector** | 带方向的数（例如带方向的风速），也可以包含许多其他数字 | 1 | 小写（`y`） |
| **matrix** | 二维数字数组 | 2 | 大写（`Q`） |
| **tensor** | n 维数字数组 | 可以是任意维数；0 维张量是标量，1 维张量是向量 | 大写（`X`） | 

![scalar、vector、matrix、tensor 及其示意](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### 随机张量

我们已经知道张量用于表示某种形式的数据。

而机器学习模型（如神经网络）会对张量进行操作并在其中寻找模式。

但在用 PyTorch 构建机器学习模型时，你很少会手工创建张量（就像我们目前这样）。

相反，模型通常从大规模随机张量开始，然后在处理数据的过程中不断调整这些随机数，使其更好地表示数据。

本质上是：

`从随机数开始 -> 观察数据 -> 更新随机数 -> 再观察数据 -> 再更新随机数...`

作为数据科学家，你可以定义模型如何开始（初始化）、如何看数据（表示）以及如何更新（优化）这些随机数。

我们后面会动手实践这些步骤。

现在先看看如何创建一个随机数张量。

我们可以使用 [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) 并传入 `size` 参数。

In [ ]:
# 创建一个大小为 (3, 4) 的随机张量
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6541, 0.4807, 0.2162, 0.6168],
         [0.4428, 0.6608, 0.6194, 0.8620],
         [0.2795, 0.6055, 0.4958, 0.5483]]),
 torch.float32)

`torch.rand()` 的灵活之处在于我们可以按需调整 `size`。

例如，如果你想创建一个常见图像 shape 的随机张量 `[224, 224, 3]`（`[height, width, color_channels]`）。

In [ ]:
# 创建一个大小为 (224, 224, 3) 的随机张量
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### 全 0 与全 1

有时候你会希望用 0 或 1 来填充张量。

这在 mask（掩码）场景中非常常见（例如把某些位置置 0，告诉模型这些值不需要学习）。

让我们用 [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html) 创建一个全 0 张量。

同样，`size` 参数依然关键。

In [ ]:
# 创建一个全 0 张量
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

同理，我们也可以创建全 1 张量，只需要使用 [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html)。

In [ ]:
# 创建一个全 1 张量
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### 创建数值区间与同形张量

有时候你可能想要一个数值区间，例如 1 到 10，或 0 到 100。

你可以使用 `torch.arange(start, end, step)`。

其中：
* `start` = 区间起点（例如 0）
* `end` = 区间终点（例如 10）
* `step` = 步长，即每个值之间间隔多少（例如 1）

> **注意：** 在 Python 中，你可以使用 `range()` 创建区间；但在 PyTorch 中，`torch.range()` 已被弃用，未来可能报错。

In [ ]:
# 使用 torch.arange()，torch.range() 已弃用
zero_to_ten_deprecated = torch.range(0, 10) # 注意：未来可能报错

# 创建 0 到 10 的数值区间
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_3695928/193451495.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

有时你会希望创建一个张量，它与另一个张量 shape 相同，但内容类型不同。

例如，创建一个与前一个张量 shape 相同的全 0 张量。

这时可以使用 [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) 或 [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html)。它们会分别返回与 `input` 同 shape 的全 0 或全 1 张量。

In [ ]:
# 也可以创建与另一个张量同形状的全 0 张量
ten_zeros = torch.zeros_like(input=zero_to_ten) # shape 将保持一致
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 张量数据类型（datatypes）

PyTorch 提供了许多不同的[张量数据类型](https://pytorch.org/docs/stable/tensors.html#data-types)。

有些类型更适合 CPU，有些更适合 GPU。

理解每种类型的使用场景需要一些时间。

通常如果你看到 `torch.cuda`，说明这个张量在 GPU 上使用（因为 Nvidia GPU 使用名为 CUDA 的计算工具链）。

最常见的类型（通常也是默认类型）是 `torch.float32` 或 `torch.float`。

它被称为“32-bit floating point（32 位浮点数）”。

此外还有 16 位浮点（`torch.float16` 或 `torch.half`）和 64 位浮点（`torch.float64` 或 `torch.double`）。

更容易混淆的是，还有 8 位、16 位、32 位和 64 位整数类型。

以及更多类型！

In [ ]:
# 张量的默认数据类型是 float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # 默认为 None，即 torch.float32 或传入的数据类型
                               device=None, # 默认为 None，即使用默认张量设备类型
                               requires_grad=False) # 若为 True，会记录在张量上执行的运算

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

除了 shape 问题（张量形状不匹配）之外，在 PyTorch 中你最常遇到的另外两类问题是数据类型和设备问题。

例如，一个张量是 `torch.float32`，另一个是 `torch.float16`（PyTorch 通常更希望参与计算的张量格式一致）。

或者一个张量在 CPU 上，另一个在 GPU 上（PyTorch 更希望参与计算的张量位于同一设备）。

后面我们还会继续讲设备相关内容。

现在先创建一个 `dtype=torch.float16` 的张量。

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half 也可以

float_16_tensor.dtype

torch.float16

## 从张量中获取信息

当你创建了张量（或由他人、某个 PyTorch 模块为你创建了张量）后，通常会想了解它的一些信息。

我们之前已经见过这些属性，其中最常用的三个是：
* `shape` - 张量的形状是什么？（某些操作要求特定形状规则）
* `dtype` - 张量内部元素以什么数据类型存储？
* `device` - 张量存储在哪个设备上？（通常是 GPU 或 CPU）

我们创建一个随机张量并查看其细节。

In [ ]:
# 创建一个张量
some_tensor = torch.rand(3, 4)

# 查看它的详细信息
print(some_tensor)
print(f"张量形状: {some_tensor.shape}")
print(f"张量数据类型: {some_tensor.dtype}")
print(f"张量存储设备: {some_tensor.device}") # 默认会是 CPU

tensor([[0.4688, 0.0055, 0.8551, 0.0646],
        [0.6538, 0.5157, 0.4071, 0.2109],
        [0.9960, 0.3061, 0.9369, 0.7008]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


> **注意：** 当你在 PyTorch 中遇到问题时，往往都与上面这三个属性之一有关。所以当报错出现时，可以给自己唱一首小歌：
  * "*我的张量 shape 是什么？数据类型是什么？它存在哪个设备上？shape、dtype、where where where*"

## 操作张量（tensor operations）

在深度学习中，数据（图像、文本、视频、音频、蛋白质结构等）都会被表示为张量。

模型通过分析这些张量，并在其上执行一系列操作（可能是上百万次）来学习输入数据中的模式表示。

这些操作通常是以下几类的组合：
* 加法
* 减法
* 乘法（逐元素）
* 除法
* 矩阵乘法

基本就这些。当然还有一些其他操作，但这些是神经网络最基础的积木。

只要把这些积木以正确方式组合起来，你就能构建非常复杂的神经网络（就像乐高一样）。

### 基础操作

先从几个最基础的操作开始：加法（`+`）、减法（`-`）、乘法（`*`）。

它们的行为和你直觉中的一致。

In [ ]:
# 创建一个张量并给它加一个数
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# 乘以 10
tensor * 10

tensor([10, 20, 30])

注意，上面的张量值并没有变成 `tensor([110, 120, 130])`，因为张量中的值只有在重新赋值后才会改变。

In [ ]:
# 张量不会变化，除非重新赋值
tensor

tensor([1, 2, 3])

我们来减一个数，这次把结果重新赋值给 `tensor` 变量。

In [ ]:
# 减法并重新赋值
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# 加法并重新赋值
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch 还内置了很多函数，例如 [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul)（multiplication 的缩写）和 [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) 来执行基础运算。

In [ ]:
# 也可以使用 torch 函数
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# 原始张量依然没有变化
tensor

tensor([1, 2, 3])

不过更常见的写法是使用操作符 `*`，而不是 `torch.mul()`。

In [ ]:
# 逐元素乘法（每个元素与对应位置相乘，索引 0->0, 1->1, 2->2）
print(tensor, "*", tensor)
print("结果:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### 矩阵乘法（非常关键）

在机器学习和深度学习算法（如神经网络）中，最常见的操作之一是[矩阵乘法](https://www.mathsisfun.com/algebra/matrix-multiplying.html)。

PyTorch 在 [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) 方法中实现了矩阵乘法功能。

你需要记住矩阵乘法的两条核心规则：

1. **内维度** 必须匹配：
  * `(3, 2) @ (3, 2)` 不能工作
  * `(2, 3) @ (3, 2)` 可以工作
  * `(3, 2) @ (2, 3)` 可以工作
2. 结果矩阵的 shape 由 **外维度** 决定：
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **注意：** 在 Python 中，`@` 是矩阵乘法符号。

> **资源：** 你可以在 [PyTorch 文档](https://pytorch.org/docs/stable/generated/torch.matmul.html) 中查看使用 `torch.matmul()` 的完整规则。

我们创建一个张量，并对其进行逐元素乘法和矩阵乘法。


In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

逐元素乘法和矩阵乘法的关键区别在于是否进行求和。

对于值为 `[1, 2, 3]` 的 `tensor` 变量：

| 运算 | 计算方式 | 代码 |
| ----- | ----- | ----- |
| **逐元素乘法** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **矩阵乘法** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |


In [ ]:
# 逐元素矩阵乘法
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# 矩阵乘法
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# 也可以使用 "@" 符号做矩阵乘法，但不推荐
tensor @ tensor

tensor(14)

你可以手写矩阵乘法，但不推荐。

内置的 `torch.matmul()` 更快。

In [ ]:
%%time
# 手动实现矩阵乘法
# （尽量避免使用 for 循环做此类运算，它们计算开销较高）
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 773 µs, sys: 0 ns, total: 773 µs
Wall time: 499 µs


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 146 µs, sys: 83 µs, total: 229 µs
Wall time: 171 µs


tensor(14)

## 深度学习中最常见的错误之一（形状错误）

由于深度学习的大量计算都依赖矩阵运算，而矩阵对可组合的 shape 和尺寸有严格要求，因此 shape 不匹配是深度学习中最常见的错误之一。

In [ ]:
# shape 必须匹配正确
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # （这里会报错）

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

要让 `tensor_A` 和 `tensor_B` 可以做矩阵乘法，需要让它们的内维度一致。

一种方法是使用 **transpose（转置）**（交换给定张量的维度）。

在 PyTorch 中可以这样做：
* `torch.transpose(input, dim0, dim1)` - 其中 `input` 是要转置的张量，`dim0` 和 `dim1` 是要交换的维度。
* `tensor.T` - 其中 `tensor` 是要转置的张量。

我们先试第二种。

In [ ]:
# 查看 tensor_A 和 tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# 查看 tensor_A 和 tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# 当 tensor_B 被转置后，运算就能正常进行
print(f"原始形状: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"新形状: tensor_A = {tensor_A.shape}（与上方相同）, tensor_B.T = {tensor_B.T.shape}\n")
print(f"执行乘法: {tensor_A.shape} * {tensor_B.T.shape} <- 内维度匹配\n")
print("输出:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\n输出形状: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


你也可以使用 [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html)，它是 `torch.matmul()` 的简写。

In [ ]:
# torch.mm 是 matmul 的快捷写法
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

如果不做转置，矩阵乘法规则就不满足，因此会像上面那样报错。

来看一个可视化示例：

![矩阵乘法可视化示意](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

你也可以在 http://matrixmultiplication.xyz/ 创建这样的矩阵乘法可视化。

> **注意：** 这种矩阵乘法也被称为两个矩阵的 [**dot product（点积）**](https://www.mathsisfun.com/algebra/vectors-dot-product.html)。


神经网络中充满了矩阵乘法和点积。

[`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) 模块（后面会看到它的实际用法），也叫前馈层（feed-forward layer）或全连接层（fully connected layer），实现了输入 `x` 与权重矩阵 `A` 之间的矩阵乘法。

$$
y = x\cdot{A^T} + b
$$

其中：
* `x` 是层的输入（深度学习通常是多层堆叠而成，比如 `torch.nn.Linear()` 与其他层）。
* `A` 是该层创建的权重矩阵，初始通常是随机数，并会在神经网络学习过程中不断调整，以更好表示数据模式（注意这里的 `T`，表示权重矩阵会被转置）。

In [ ]:
# 线性层从随机权重矩阵开始，因此我们先设置可复现性（后面会详细讲）
torch.manual_seed(42)
# 这里内部会用到矩阵乘法
linear = torch.nn.Linear(in_features=2, # in_features = 与输入内维度匹配
                         out_features=6) # out_features = 描述外维度输出
x = tensor_A
output = linear(x)
print(f"输入形状: {x.shape}\n")
print(f"输出:\n{output}\n\n输出形状: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


> **问题：** 如果把上面的 `in_features` 从 2 改成 3，会发生什么？会报错吗？你该如何调整输入 `x` 的 shape 来适配这个错误？提示：上面我们对 `tensor_B` 做了什么操作？

如果你之前没接触过，矩阵乘法一开始可能会有些绕。

但当你多练几次，甚至拆开看过几个神经网络之后，你会发现它几乎无处不在。

记住，矩阵乘法非常关键。

![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*当你深入神经网络层并开始自己搭建网络时，你会在各处看到矩阵乘法。**来源：** https://marksaroufim.substack.com/p/working-class-deep-learner*

### 查找 min、max、mean、sum 等（聚合）

我们已经看过一些操作张量的方法，接下来看看如何对张量做聚合（从更多数值汇总成更少数值）。

先创建一个张量，再找它的 max、min、mean 和 sum。




In [ ]:
# 创建一个张量
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

现在做一些聚合计算。

In [ ]:
print(f"最小值: {x.min()}")
print(f"最大值: {x.max()}")
# print(f"均值: {x.mean()}") # 这里会报错
print(f"均值: {x.type(torch.float32).mean()}") # 不是 float 类型会失败
print(f"总和: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **注意：** 你会发现某些方法（例如 `torch.mean()`）要求张量是 `torch.float32`（最常见）或其他特定数据类型，否则操作会失败。

你也可以使用 `torch` 的函数形式完成同样操作。

In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### 位置上的最小值/最大值

你还可以分别用 [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) 和 [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) 找到张量中最大值或最小值所在的索引位置。

当你只关心最大值（或最小值）出现的位置，而不关心具体数值时，这很有帮助（后面讲 [softmax 激活函数](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html) 时会再次看到）。

In [ ]:
# 创建一个张量
tensor = torch.arange(10, 100, 10)
print(f"张量: {tensor}")

# 返回最大值和最小值所在索引
print(f"最大值所在索引: {tensor.argmax()}")
print(f"最小值所在索引: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### 改变张量数据类型

如前所述，深度学习运算中的常见问题之一是张量数据类型不一致。

如果一个张量是 `torch.float64`，另一个是 `torch.float32`，你就可能遇到报错。

不过这很好解决。

你可以使用 [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) 来改变张量的数据类型，其中 `dtype` 参数就是你想使用的类型。

先创建一个张量并查看其数据类型（默认是 `torch.float32`）。

In [ ]:
# 创建一个张量并检查其数据类型
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

现在我们创建一个与之前相同的张量，但把数据类型改为 `torch.float16`。



In [ ]:
# 创建一个 float16 张量
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

我们也可以类似地创建一个 `torch.int8` 张量。

In [ ]:
# 创建一个 int8 张量
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **注意：** 不同数据类型在一开始确实容易混淆。你可以这样理解：位数越低（如 32、16、8），计算机存储值的精度通常越低。更低的存储精度通常意味着更快的计算速度和更小的模型体积。移动端神经网络经常使用 8 位整数，它更小、更快，但通常不如 float32 精确。想进一步了解可阅读[计算中的精度](https://en.wikipedia.org/wiki/Precision_(computer_science))。

 > **练习：** 到目前为止我们已经覆盖了不少张量方法，但 [`torch.Tensor` 文档](https://pytorch.org/docs/stable/tensors.html) 里还有很多。建议花 10 分钟滚动浏览，挑几个你感兴趣的方法，点开后自己写代码试一试。

### Reshaping、stacking、squeezing 与 unsqueezing

很多时候你希望改变张量的形状或维度，但不改变其中的数值。

常见方法有：

| 方法 | 一句话说明 |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | 将 `input` 重塑为 `shape`（若兼容）；也可用 `torch.Tensor.reshape()`。 |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | 返回原始张量在新 `shape` 下的视图，和原张量共享同一份数据。 |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | 沿新维度 `dim` 拼接一组 `tensors`，所有张量必须同尺寸。 |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | 压缩 `input`，移除值为 `1` 的所有维度。 |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | 在 `dim` 位置新增一个值为 `1` 的维度并返回。 | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | 返回原始 `input` 的一个 *view*，其维度顺序按 `dims` 重排。 | 

为什么要做这些？

因为深度学习模型（神经网络）本质上就是不断操作张量。而矩阵乘法有严格 shape 规则，一旦 shape 不匹配就会报错。这些方法能帮助你确保张量中的正确元素与其他张量中的正确元素进行运算。

我们来试试。

先创建一个张量。

In [ ]:
# 创建一个张量
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

现在用 `torch.reshape()` 增加一个额外维度。

In [ ]:
# 增加一个额外维度
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

我们也可以用 `torch.view()` 改变视图。

In [ ]:
# 改变视图（保留原始数据，但改变查看方式）
# 更多说明: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

但要记住，用 `torch.view()` 改变张量视图，本质上只是为 *同一个* 张量创建了新视图。

因此改变这个视图，也会改变原始张量。

In [ ]:
# 修改 z 会同步影响 x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

如果我们想把新张量自身堆叠多次，可以使用 `torch.stack()`。

In [ ]:
# 将张量在新维度上堆叠
x_stacked = torch.stack([x, x, x, x], dim=0) # 可尝试把 dim 改为 1 观察变化
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

那如果要移除张量中所有单维度呢？

可以使用 `torch.squeeze()`（我把它记成把张量“挤压”到只保留大于 1 的维度）。

In [ ]:
print(f"原始张量: {x_reshaped}")
print(f"原始形状: {x_reshaped.shape}")

# 从 x_reshaped 中移除额外维度
x_squeezed = x_reshaped.squeeze()
print(f"\n新张量: {x_squeezed}")
print(f"新形状: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


反过来，如果要做 `torch.squeeze()` 的逆操作，可以用 `torch.unsqueeze()` 在指定索引处增加一个值为 1 的维度。

In [ ]:
print(f"原始张量: {x_squeezed}")
print(f"原始形状: {x_squeezed.shape}")

## 使用 unsqueeze 增加额外维度
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n新张量: {x_unsqueezed}")
print(f"新形状: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


你还可以用 `torch.permute(input, dims)` 重排轴顺序，其中 `input` 会被转换为一个具有新 `dims` 的 *view*。

In [ ]:
# 创建特定形状的张量
x_original = torch.rand(size=(224, 224, 3))

# 对原始张量做 permute 以重排轴顺序
x_permuted = x_original.permute(2, 0, 1) # 轴变换: 0->1, 1->2, 2->0

print(f"原始形状: {x_original.shape}")
print(f"新形状: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


> **注意**: 因为 permute 返回的是一个 *view*（与原始张量共享数据），所以重排后张量的值与原始张量相同；若你修改该 view 的值，也会影响原始张量。

## 索引（从张量中选择数据）

有时候你只想取张量中的特定数据（例如只取第一列或第二行）。

这时可以使用索引。

如果你做过 Python 列表或 NumPy 数组索引，那么 PyTorch 张量索引会非常类似。

In [ ]:
# 创建一个张量
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

索引时取值顺序是外层维度 -> 内层维度（可对照方括号理解）。

In [ ]:
# 逐层方括号索引
print(f"第一层方括号:\n{x[0]}") 
print(f"第二层方括号: {x[0][0]}") 
print(f"第三层方括号: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


你也可以使用 `:` 指定“这个维度的所有值”，再用逗号 `,` 增加下一维索引。

In [ ]:
# 获取第 0 维全部值，以及第 1 维索引 0 的值
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# 获取第 0、1 维全部值，以及第 2 维索引 1 的值
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# 获取第 0 维全部值，以及第 1、2 维索引 1 的值
x[:, 1, 1]

tensor([5])

In [ ]:
# 获取第 0 维与第 1 维索引 0，及第 2 维全部值
x[0, 0, :] # 等价于 x[0][0]

tensor([1, 2, 3])

索引在一开始确实容易混淆，尤其是更大维度的张量（我现在也常常要试几次才能写对）。但只要多练习，并遵循数据探索者的口号（***visualize, visualize, visualize***），你会越来越熟练。

## PyTorch 张量与 NumPy

由于 NumPy 是非常流行的 Python 数值计算库，PyTorch 也提供了良好的互操作能力。

NumPy 与 PyTorch 互转最常用的两个方法是：
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy 数组 -> PyTorch 张量。
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch 张量 -> NumPy 数组。

我们来试试。

In [ ]:
# NumPy array 转 tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **注意：** 默认情况下，NumPy 创建的数组数据类型是 `float64`，转换为 PyTorch 张量后会保留该类型（如上）。

> 但很多 PyTorch 计算默认使用 `float32`。

> 所以如果你希望把 NumPy array（float64）-> PyTorch tensor（float64）-> PyTorch tensor（float32），可以使用 `tensor = torch.from_numpy(array).type(torch.float32)`。

由于我们上面重新赋值了 `tensor`，因此修改 tensor 时，array 会保持不变。

In [ ]:
# 修改 array，保持 tensor 不变
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

如果你想从 PyTorch tensor 转回 NumPy array，可以调用 `tensor.numpy()`。

In [ ]:
# Tensor 转 NumPy array
tensor = torch.ones(7) # 创建 dtype=float32 的全 1 张量
numpy_tensor = tensor.numpy() # 除非手动修改，否则会是 dtype=float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

同样适用上面的规则：如果你修改原始 `tensor`，新的 `numpy_tensor` 会保持不变。

In [ ]:
# 修改 tensor，保持 array 不变
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## 可复现性（尽量减少随机中的随机）

随着你对神经网络和机器学习理解加深，你会发现随机性在其中扮演了很大角色。

更准确地说，是伪随机。因为从设计上看，计算机本质上是确定性的（每一步都可预测），所以它生成的是“模拟随机性”（这个话题也有很多讨论，感兴趣你可以继续深入）。

这与神经网络和深度学习有什么关系？

我们前面提到过，神经网络通常从随机数出发去描述数据模式（这些初始描述通常很粗糙），再通过张量运算（以及一些我们还没讲到的机制）不断改进这些随机数，以更好地表示数据中的模式。

简要来说：

``从随机数开始 -> 进行张量运算 -> 持续改进（反复迭代）``

In [ ]:
import torch

# 创建两个随机张量
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Tensor A 与 Tensor B 是否相等？（任意位置）")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

正如你预期的那样，这两个张量的值不同。

但如果你想创建两个值 *相同* 的随机张量呢？

也就是说它们仍然是随机值，但“随机风味”一致。

这时就要用到 [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html)。其中 `seed` 是整数（比如 `42`，也可以是任意整数），用于固定随机性的生成轨迹。

我们来试试，创建一些带固定“风味”的随机张量。

In [ ]:
import torch
import random

# # 设置随机种子
RANDOM_SEED=42 # 可尝试改成其他值，观察下面数值变化
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# 每次新调用 rand() 前都要重新设置种子
# 否则 tensor_D 会与 tensor_C 不同
torch.random.manual_seed(seed=RANDOM_SEED) # 可尝试注释掉此行观察变化
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Tensor C 与 Tensor D 是否相等？（任意位置）")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

很好！

看起来设置随机种子生效了。

> **资源：** 我们刚讲到的只是 PyTorch 可复现性的入门。若想深入了解可复现性和随机种子，可以看：
> * [PyTorch 可复现性文档](https://pytorch.org/docs/stable/notes/randomness.html)（建议先读 10 分钟，即便现在不完全理解，也先建立认知）。
> * [Wikipedia 的随机种子页面](https://en.wikipedia.org/wiki/Random_seed)（对随机种子与伪随机会有不错的概览）。

## 在 GPU 上运行张量（并加速计算）

深度学习算法需要大量数值运算。

默认情况下，这些运算通常在 CPU（中央处理器）上执行。

但还有另一类常见硬件是 GPU（图形处理器），它在神经网络常见运算（如矩阵乘法）上通常比 CPU 快得多。

你的电脑可能就有 GPU。

如果有，训练神经网络时应尽量使用它，因为它往往能显著缩短训练时间。

要让 PyTorch 用上 GPU，通常有两个步骤：先拿到 GPU，再让 PyTorch 使用它。

> **注意：** 本课程里提到的“GPU”默认是指支持 [Nvidia CUDA](https://developer.nvidia.com/cuda-gpus) 的 GPU（除非另有说明）。CUDA 是一个计算平台与 API，使 GPU 不仅能做图形计算，也能做通用计算。



### 1. 获取 GPU

你可能已经熟悉 GPU 了。如果不熟悉，也有几种常见方式可以获得 GPU。

| **方式** | **配置难度** | **优点** | **缺点** | **如何配置** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | 简单 | 免费、几乎零配置、可通过链接轻松共享 | 数据输出不持久、算力有限、会超时 | [参考 Google Colab 指南](https://colab.research.google.com/notebooks/gpu.ipynb) |
| 自己的机器 | 中等 | 所有内容本地运行 | GPU 并非免费，前期成本高 | 参考 [PyTorch 本地安装指南](https://pytorch.org/get-started/locally/) |
| 云计算（AWS、GCP、Azure） | 中等-较难 | 前期成本较小、可获得几乎无限算力 | 持续运行成本可能较高、配置需要时间 | 参考 [PyTorch 云平台指南](https://pytorch.org/get-started/cloud-partners/) |

还有其他 GPU 方案，但目前这三种已经够用。

我个人会组合使用 Google Colab 和本地电脑做小规模实验（以及制作这门课），当需要更大算力时再上云。

> **资源：** 如果你打算购买自己的 GPU 但不确定选型，[Tim Dettmers 的这份指南](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/) 非常好。

要检查是否能访问 Nvidia GPU，可以运行 `!nvidia-smi`，其中 `!`（也叫 bang）表示“在命令行执行”。


In [70]:
!nvidia-smi

Sat Jan 21 08:34:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    On   | 00000000:01:00.0 Off |                  N/A |
| 40%   30C    P8     7W / 280W |    177MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

如果你无法访问 Nvidia GPU，上面的输出通常类似：

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

这种情况下，请回到上面按安装步骤检查。

如果你有 GPU，上面的输出通常类似：

```
Wed Jan 19 22:09:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```



### 2. 让 PyTorch 在 GPU 上运行

当你拿到可用 GPU 后，下一步是让 PyTorch 用它来存储数据（张量）和计算（张量运算）。

可以使用 [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html) 包。

与其讲概念，不如直接试。

你可以用 [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available) 检查 PyTorch 是否可访问 GPU。


In [ ]:
# 检查 GPU
import torch
torch.cuda.is_available()

True

如果上面输出 `True`，说明 PyTorch 能看到并使用 GPU；如果输出 `False`，说明当前看不到 GPU，需要回到安装步骤排查。

现在假设你希望代码能在 CPU *或* GPU 上运行（若 GPU 可用则自动使用）。

这样无论你自己还是别人运行代码，都能适配其计算设备。

我们创建一个 `device` 变量来保存可用设备类型。

In [ ]:
# 设置设备类型
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

如果上面输出 `"cuda"`，表示我们可以让全部 PyTorch 代码使用可用的 CUDA 设备（GPU）；如果输出 `"cpu"`，则代码会继续在 CPU 上运行。

> **注意：** 在 PyTorch 中，最佳实践是写 [**device agnostic code**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code)（设备无关代码），即代码既能在 CPU（总可用）运行，也能在 GPU（可用时）运行。

如果你想更快计算，可以用 GPU；如果想 *更快更多*，可以使用多 GPU。

你可以用 [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count) 统计 PyTorch 可访问的 GPU 数量。

In [ ]:
# 统计设备数量
torch.cuda.device_count()

1

了解 PyTorch 可访问 GPU 的数量很有帮助，比如你希望某个任务跑在一个 GPU、另一个任务跑在另一个 GPU（PyTorch 也支持跨 *全部* GPU 运行一个任务）。

### 2.1 在 Apple Silicon 上运行 PyTorch

要在 Apple 的 M1/M2/M3 GPU 上运行 PyTorch，可以使用 [`torch.backends.mps`](https://pytorch.org/docs/stable/notes/mps.html) 模块。

请确保 macOS 和 PyTorch 版本都已更新。

你可以用 `torch.backends.mps.is_available()` 检查 PyTorch 是否可访问 GPU。

In [ ]:
# 检查 Apple Silicon GPU
import torch
torch.backends.mps.is_available() # 注意：如果你不是在 Mac 上运行，这里会是 False

True

In [ ]:
# 设置设备类型
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

和前面一样，如果上面输出 `"mps"`，说明我们可以让 PyTorch 代码使用可用的 Apple Silicon GPU。

In [ ]:
if torch.cuda.is_available():
    device = "cuda" # 使用 NVIDIA GPU（若可用）
elif torch.backends.mps.is_available():
    device = "mps" # 使用 Apple Silicon GPU（若可用）
else:
    device = "cpu" # 没有 GPU 时默认使用 CPU

### 3. 把张量（和模型）放到 GPU 上

你可以对张量（模型后面会讲）调用 [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) 把它放到指定设备上。这里的 `device` 是目标设备。

为什么要这样做？

GPU 的数值计算通常比 CPU 快很多；如果没有 GPU，由于我们写的是 **设备无关代码**（见上文），代码会自动回退到 CPU。

> **注意：** 用 `to(device)` 把张量放到 GPU（例如 `some_tensor.to(device)`）会返回该张量的一个副本，也就是 CPU 与 GPU 上都会有。若要覆盖原变量，需要重新赋值：
>
> `some_tensor = some_tensor.to(device)`

我们来创建一个张量并把它放到 GPU（如果可用）。

In [ ]:
# 创建张量（默认在 CPU）
tensor = torch.tensor([1, 2, 3])

# 张量当前不在 GPU
print(tensor, tensor.device)

# 将张量移动到 GPU（如果可用）
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

如果你有可用 GPU，上面代码会输出类似：

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

注意第二个张量有 `device='cuda:0'`，表示它存放在第 0 张可用 GPU 上（GPU 从 0 开始编号；若有两张，则分别是 `'cuda:0'` 和 `'cuda:1'`，依此类推到 `'cuda:n'`）。


### 4. 把张量移回 CPU

如果我们想把张量移回 CPU 呢？

例如，当你想让张量与 NumPy 交互时就需要这样做（NumPy 不使用 GPU）。

先试试在 `tensor_on_gpu` 上直接调用 [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html)。

In [ ]:
# 如果张量在 GPU 上，无法直接转为 NumPy（这里会报错）
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

正确做法是先用 [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html) 把张量放回 CPU，再与 NumPy 配合。

这会把张量复制到 CPU 内存，使其可被 CPU/NumPy 使用。

In [ ]:
# 将张量复制回 cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

上面的结果是在 CPU 内存中返回了 GPU 张量的副本，因此原始张量仍然在 GPU 上。

In [77]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 练习

所有练习都围绕上面的代码实践展开。

你应该可以通过回看各节内容，或参考给出的资源来完成。

**资源：**

* [00 章练习模板 notebook](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb)。
* [00 章示例解答 notebook](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb)（请先自己做再看答案）。

1. 文档阅读 - 深度学习（以及编程学习）很重要的一部分是熟悉你使用框架的文档。本课程后续会频繁使用 PyTorch 文档。建议先花 10 分钟读下面内容（现在不完全理解也没关系，重点是先建立认知）：[`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) 与 [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics)。
2. 创建一个 shape 为 `(7, 7)` 的随机张量。
3. 用第 2 步的张量与另一个 shape 为 `(1, 7)` 的随机张量做矩阵乘法（提示：你可能需要转置第二个张量）。
4. 将随机种子设为 `0`，重新完成第 2、3 题。
5. 说到随机种子，我们看到了 `torch.manual_seed()`，那 GPU 上有没有等价方法？（提示：查 `torch.cuda` 文档）。如果有，把 GPU 随机种子设为 `1234`。
6. 创建两个 shape 为 `(2, 3)` 的随机张量，并都发送到 GPU（你需要可用 GPU）。创建时设 `torch.manual_seed(1234)`（这不一定是 GPU 随机种子）。
7. 对第 6 题创建的张量执行矩阵乘法（同样，你可能需要调整其中一个张量的 shape）。
8. 找出第 7 题输出结果的最大值和最小值。
9. 找出第 7 题输出结果中最大值和最小值对应的索引。
10. 创建一个 shape 为 `(1, 1, 1, 10)` 的随机张量，然后创建一个移除所有值为 `1` 维度的新张量，得到 shape `(10)`。创建时设 seed 为 `7`，并打印第一个张量及其 shape，以及第二个张量及其 shape。

## 拓展学习

* 花 1 小时学习 [PyTorch 基础教程](https://pytorch.org/tutorials/beginner/basics/intro.html)（推荐先看 [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) 和 [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)）。
* 想进一步理解张量如何表示数据，可以看这个视频：[What's a tensor?](https://youtu.be/f5liqUk0ZTw)