# 00. PyTorch 基础练习

### 1. 阅读文档

学习深度学习（以及编程本身）很重要的一环，是熟悉你正在使用框架的官方文档。课程后续会频繁使用 PyTorch 文档，所以建议先花 10 分钟阅读以下内容（暂时看不懂也没关系，当前重点是建立认知）：
  * [`torch.Tensor` 文档](https://pytorch.org/docs/stable/tensors.html#torch-tensor)。
  * [`torch.cuda` 文档](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics)。



In [ ]:
# 本题无需代码（文档阅读）

### 2. 创建一个形状为 `(7, 7)` 的随机张量。


In [ ]:
# 导入 torch


# 创建随机张量


### 3. 使用第 2 题中的张量，与另一个形状为 `(1, 7)` 的随机张量做矩阵乘法（提示：你可能需要转置第二个张量）。

In [ ]:
# 再创建一个随机张量

# 执行矩阵乘法


### 4. 将随机种子设置为 `0`，然后重新完成第 2 和第 3 题。

输出应为：
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# 设置手动随机种子


# 创建两个随机张量


# 矩阵乘法


### 5. 说到随机种子，我们已经看到如何用 `torch.manual_seed()` 设置它。那么 GPU 上有对应方法吗？（提示：需要查看 `torch.cuda` 文档）
  * 如果有，把 GPU 的随机种子设置为 `1234`。

In [ ]:
# 在 GPU 上设置随机种子



### 6. 创建两个形状为 `(2, 3)` 的随机张量，并都发送到 GPU（本题需要可用 GPU）。创建张量时设置 `torch.manual_seed(1234)`（不必是 GPU 专用随机种子）。输出应类似：

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# 设置随机种子


# 检查是否可用 GPU

# 在 GPU 上创建两个随机张量



### 7. 对第 6 题创建的张量执行矩阵乘法（同样，你可能需要调整其中一个张量的形状）。

输出应类似：
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# 对 tensor_A 和 tensor_B 执行矩阵乘法


### 8. 找出第 7 题输出的最大值和最小值。

In [ ]:
# 找最大值

# 找最小值


### 9. 找出第 7 题输出中最大值和最小值对应的索引。

In [ ]:
# 找最大值索引


# 找最小值索引



### 10. 创建一个形状为 `(1, 1, 1, 10)` 的随机张量，然后去掉所有值为 `1` 的维度，得到形状 `(10)` 的新张量。创建时将种子设为 `7`，并打印第一个张量及其形状，以及第二个张量及其形状。

输出应类似：

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# 设置随机种子


# 创建随机张量


# 去掉长度为 1 的维度


# 打印张量及其形状
