<a href="https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/extras/pytorch_cheatsheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="在 Colab 中打开"/></a> 

# PyTorch 速查表

PyTorch 中最常用的一些命令和设置。

> **注意：** 查找 PyTorch 相关函数和用法时，最好的方法之一就是搜索 "pytorch how to make a convolutional neural network"、"pytorch transformer layers" 或 "pytorch loss functions"。我自己也经常这样做。

## 导入

你可以通过 [PyTorch 安装页面](https://pytorch.org/get-started/locally/) 在各种平台上安装 PyTorch。

In [ ]:
import torch

# 查看版本
print(f"PyTorch version: {torch.__version__}")

PyTorch version: 1.13.1


In [ ]:
# 也可以导入常用缩写 "nn"，即 "Neural Networks"
from torch import nn

# 在 PyTorch 中，几乎所有东西都叫 "Module"（你通过把多个 Module 堆叠起来来构建神经网络）
this_is_a_module = nn.Linear(in_features=1,
                             out_features=1)
print(type(this_is_a_module))

<class 'torch.nn.modules.linear.Linear'>


### 数据导入

由于机器学习的大部分工作都是在数据中寻找模式，因此了解如何在 PyTorch 中处理数据集很重要。

In [ ]:
# 导入 PyTorch 的 Dataset（你可以把数据存放在这里）和 DataLoader（你可以从这里加载数据）
from torch.utils.data import Dataset, DataLoader

## 创建张量

PyTorch 的一个主要用途是加速深度学习计算。

而深度学习通常涉及对大型张量的操作（张量就是由很多数字组成的多维集合）。

PyTorch 提供了许多创建张量的方法。

> **注意：** 如果你想更全面地了解如何用 PyTorch 创建张量，可以查看 [00. PyTorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/)。

In [ ]:
# 创建一个单个数值的张量（标量）
scalar = torch.tensor(7)

In [ ]:
# 创建一个随机张量
random_tensor = torch.rand(size=(3, 4)) # 这会创建一个 3x4 的张量，但你可以按自己的需要调整形状

In [ ]:
# 乘以两个随机张量
random_tensor_1 = torch.rand(size=(3, 4))
random_tensor_2 = torch.rand(size=(3, 4))
random_tensor_3 = random_tensor_1 * random_tensor_2 # PyTorch 支持 Python 中大多数数学运算符（+、*、-、/）

## 领域库

根据你正在处理的具体问题，PyTorch 提供了多个领域库。

- **[TorchVision](https://pytorch.org/vision/stable/index.html)** - PyTorch 自带的计算机视觉库。
- **[TorchText](https://pytorch.org/text/stable/index.html)** - PyTorch 内置的文本领域库。
- [**TorchAudio**](https://pytorch.org/audio/stable/index.html) - PyTorch 的音频领域库。
- **[TorchRec](https://pytorch.org/torchrec/)** - PyTorch 最新的内置领域库，用于借助深度学习驱动推荐系统。

### 计算机视觉

> **注意：** 如果你想深入了解 PyTorch 中的计算机视觉，可以查看 [03. PyTorch Computer Vision](https://www.learnpytorch.io/03_pytorch_computer_vision/)。

In [ ]:
# 基础计算机视觉库
import torchvision

# TorchVision 的其他组件（预置数据集、预训练模型和图像变换）
from torchvision import datasets, models, transforms 

### 文本与自然语言处理（NLP）

In [ ]:
# 基础文本和自然语言处理库
import torchtext

# TorchText 的其他组件（预置数据集、预训练模型和文本变换）
from torchtext import datasets, models, transforms

### 音频与语音

In [ ]:
# 基础音频和语音处理库
import torchaudio

# TorchAudio 的其他组件（预置数据集、预训练模型和文本变换）
from torchaudio import datasets, models, transforms

### 推荐系统

> **注意：** 这个库目前仍处于 beta 版本，安装说明请见 [GitHub 页面](https://github.com/pytorch/torchrec#installation)。

In [ ]:
# # 基础推荐系统库
# 导入 torchrec

# # TorchRec 的其他组件
# 从 torchrec 导入 datasets 和 models


## 设备无关代码（在 CPU、GPU 或 MPS 上使用 PyTorch）

深度学习的大量工作都涉及对张量进行计算。

对张量的计算通常在 GPU（图形处理器，通常来自 NVIDIA）上比在 CPU（中央处理器）上快得多。

MPS 指的是 "Metal Performance Shader"，这是苹果的 GPU（M1、M1 Pro、M2 等）。

建议使用你手头最快的硬件进行训练，通常优先级是：NVIDIA GPU（`"cuda"`）> MPS 设备（`"mps"`）> CPU（`"cpu"`）。

* 关于如何让 [PyTorch 在 NVIDIA GPU 上运行（使用 CUDA）](https://pytorch.org/docs/stable/cuda.html) 的更多信息，请查看 [00. PyTorch Fundamentals 第 2 节：让 PyTorch 在 GPU 上运行](https://www.learnpytorch.io/00_pytorch_fundamentals/#2-getting-pytorch-to-run-on-the-gpu)。
* 关于使用 MPS 后端运行 PyTorch（在 Mac GPU 上运行 PyTorch）的更多信息，请查看 [PyTorch 文档](https://pytorch.org/docs/stable/notes/mps.html)。

> **注意：** 建议在工作流一开始就设置设备无关代码。

In [ ]:
# 设置设备无关代码
if torch.cuda.is_available():
    device = "cuda" # NVIDIA GPU
elif torch.backends.mps.is_available():
    device = "mps" # Apple GPU
else:
    device = "cpu" # 如果没有 NVIDIA GPU/Apple GPU，则默认使用 CPU

print(f"Using device: {device}")

Using device: mps


### 将张量发送到目标设备

你可以通过 `.to("device_name")` 方法把 PyTorch 中的对象（模型和张量）移动到不同设备上。

In [ ]:
# 创建一个张量
x = torch.tensor([1, 2, 3])
print(x.device) # 默认在 CPU 上

# 将张量发送到目标设备
x = x.to(device)
print(x.device)

cpu
mps:0


## 设置随机种子

许多机器学习和深度学习工作都涉及在张量中使用随机数，然后再通过这些随机数来寻找或表示真实数据中的模式。

In [ ]:
import torch

# 设置随机种子（你可以把它设成任何数字，它会用这个数字给随机性“调味”）
torch.manual_seed(42)

# 创建两个随机张量
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(42) # 再次设置种子（你可以试着注释掉这一行，看看会发生什么）
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

你也可以在 GPU（CUDA 设备）上设置随机种子。

In [ ]:
# 在 GPU 上设置随机种子
torch.cuda.manual_seed(42)

## 神经网络

PyTorch 提供了非常全面的预置神经网络组件库（在 PyTorch 生态中，很多这类组件都叫做“模块”）。

从最基础的层面看，神经网络就是若干 *层* 叠在一起。每一层都会对输入执行某种操作，并产生一个输出。

这些层如何组合在一起，取决于你正在处理的问题。

机器学习中最活跃的研究领域之一，就是如何把神经网络的各层组合起来（而且最佳答案一直在变化）。

PyTorch 中绝大多数神经网络组件都包含在 [`torch.nn` 包](https://pytorch.org/docs/stable/nn.html) 中（`nn` 是 neural networks 的缩写）。

In [15]:
from torch import nn

### 线性层

PyTorch 提供了若干内置的 [线性层](https://pytorch.org/docs/stable/nn.html#linear-layers)。

In [ ]:
# 创建一个具有 10 个输入特征和 10 个输出特征的线性层
linear_layer = nn.Linear(in_features=10,
                         out_features=10)

In [ ]:
# 创建一个 Identity 层
identity_layer = nn.Identity()

### 卷积层（用于构建卷积神经网络，CNN）

PyTorch 提供了 [若干内置卷积层](https://pytorch.org/docs/stable/nn.html#convolution-layers)。

卷积层的命名通常遵循 `torch.nn.ConvXd`，其中 `X` 可以是 `1`、`2` 或 `3`。

`X` 表示卷积操作所作用的维度数量。例如，`1` 表示一维文本，`2` 表示二维图像（高 x 宽），`3` 表示 3D 对象，例如视频（视频可以看作带有时间维度的一系列图像，即 高 x 宽 x 时间）。

> **注意：** 如果你想进一步了解如何使用 PyTorch 构建用于计算机视觉的卷积神经网络，可以查看 [03. PyTorch Computer Vision 第 7.2 节：构建卷积神经网络（CNN）](https://www.learnpytorch.io/03_pytorch_computer_vision/#7-model-2-building-a-convolutional-neural-network-cnn)。

In [ ]:
# 创建一个 Conv1d 层（通常用于具有单一维度的文本）
conv1d = nn.Conv1d(in_channels=1,
                   out_channels=10,
                   kernel_size=3)

In [ ]:
# 创建一个 Conv2d 层（通常用于具有高 x 宽 维度的图像）
conv2d = nn.Conv2d(in_channels=3, # 彩色图像有 3 个通道（红、绿、蓝）
                   out_channels=10,
                   kernel_size=3)

In [ ]:
# 创建一个 Conv3d 层（通常用于具有高 x 宽 x 时间 维度的视频）
conv3d = nn.Conv3d(in_channels=3,
                   out_channels=10,
                   kernel_size=3)

### Transformer 层（用于构建 Transformer 模型）

PyTorch 提供了内置的 Transformer 层，相关内容可以参见论文 [Attention Is All You Need](https://arxiv.org/abs/1706.03762)。

In [ ]:
# 创建一个 Transformer 模型（基于论文 "Attention Is All You Need" - https://arxiv.org/abs/1706.03762）
transformer_model = nn.Transformer()

In [ ]:
# 创建一个单个 Transformer 编码器单元
transformer_encoder = nn.TransformerEncoderLayer(d_model=768, # embedding 维度
                                                 nhead=12) # 注意力头数量

In [ ]:
# 将多个 Transformer 编码器单元堆叠起来
transformer_encoder_stack = nn.TransformerEncoder(encoder_layer=transformer_encoder, # 来自上面
                                                  num_layers=6) # 将 6 个 Transformer 编码器堆叠在一起

In [ ]:
# 创建一个单个 Transformer 解码器单元
transformer_decoder = nn.TransformerDecoderLayer(d_model=768,
                                                 nhead=12)

In [ ]:
# 将多个 Transformer 解码器单元堆叠起来
transformer_decoder_stack = nn.TransformerDecoder(decoder_layer=transformer_decoder, # 来自上面
                                                  num_layers=6) # 将 6 个 Transformer 解码器堆叠在一起

### 循环层（用于构建循环神经网络，RNN）

PyTorch 内置支持 [循环神经网络层](https://pytorch.org/docs/stable/nn.html#recurrent-layers)，例如 [长短期记忆网络（LSTM）](https://en.wikipedia.org/wiki/Long_short-term_memory) 和 [门控循环单元（GRU）](https://en.wikipedia.org/wiki/Gated_recurrent_unit)。

In [ ]:
# 创建一个单个 LSTM 单元
lstm_cell = nn.LSTMCell(input_size=10, # 可按需要调整
                        hidden_size=10) # 可按需要调整

In [ ]:
# 将多个 LSTM 单元堆叠起来
lstm_stack = nn.LSTM(input_size=10,
                     hidden_size=10,
                     num_layers=3) # 将 3 个单独的 LSTM 单元堆叠在一起

In [ ]:
# 创建一个单个 GRU 单元
gru_cell = nn.GRUCell(input_size=10, # 可按需要调整
                      hidden_size=10) # 可按需要调整

In [ ]:
# 将多个 GRU 单元堆叠起来
gru_stack = nn.GRU(input_size=10, 
                   hidden_size=10,
                   num_layers=3) # 将 3 个单独的 GRU 单元堆叠在一起

### 激活函数

[激活函数](https://en.wikipedia.org/wiki/Activation_function) 通常位于神经网络的各层之间，用来为线性（直线）函数增加非线性（非直线）能力。

从本质上说，神经网络通常由大量线性和非线性函数组成。

PyTorch 的 `torch.nn` 中内置了 [若干非线性激活函数](https://pytorch.org/docs/stable/nn.html#non-linear-activations-weighted-sum-nonlinearity)。

其中最常见的一些包括：
* `nn.ReLU` - 也叫 [rectified linear unit](https://en.wikipedia.org/wiki/Rectifier_(neural_networks))。
* `nn.Sigmoid` - 也叫 [sigmoid function](https://en.wikipedia.org/wiki/Sigmoid_function)。
* `nn.Softmax` - 也叫 [softmax function](https://en.wikipedia.org/wiki/Softmax_function)。

> **注意：** 想了解更多，可查看 [02. PyTorch Neural Network Classification 第 6 节：缺失的一环，非线性](https://www.learnpytorch.io/02_pytorch_classification/#6-the-missing-piece-non-linearity)。

In [ ]:
# ReLU 激活函数
relu = nn.ReLU()

# Sigmoid 激活函数
sigmoid = nn.Sigmoid()

# Softmax 激活函数
softmax = nn.Softmax()

### 损失函数

损失函数用于衡量你的模型有多“错”，也就是预测值与真实目标之间偏差有多大。

理想情况下，随着训练数据和优化算法不断作用，损失值应该尽可能下降。

在 PyTorch（以及深度学习）中，损失函数也常被称为：criterion（准则）或 cost function（代价函数）。

PyTorch 在 `torch.nn` 中内置了[多种损失函数](https://pytorch.org/docs/stable/nn.html#loss-functions)。

其中最常见的包括：
* [`nn.L1Loss`](https://pytorch.org/docs/stable/generated/torch.nn.L1Loss.html#torch.nn.L1Loss) - 也称 MAE 或[平均绝对误差](https://en.wikipedia.org/wiki/Mean_absolute_error)（常用于回归问题，或预测房价这类连续数值）。
* [`nn.MSELoss`](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss) - 也称 L2Loss 或[均方误差](https://en.wikipedia.org/wiki/Mean_squared_error)（同样常用于回归问题或连续数值预测）。
* [`nn.BCEWithLogitsLoss`](https://pytorch.org/docs/stable/generated/torch.nn.BCEWithLogitsLoss.html#torch.nn.BCEWithLogitsLoss) - 也叫[二元交叉熵](https://en.wikipedia.org/wiki/Cross_entropy)，常用于二分类问题（把样本分成两类之一）。
* [`nn.CrossEntropyLoss`](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss) - 常用于多分类问题（在多个类别中进行分类）。

In [31]:
# L1Loss 损失函数
loss_fn = nn.L1Loss() # also known as MAE or mean absolute error

# MSELoss 损失函数
loss_fn = nn.MSELoss() # also known as MSE or mean squared error

# 二元交叉熵（用于二分类问题）
loss_fn = nn.BCEWithLogitsLoss()

# 交叉熵（用于多分类问题）
loss_fn = nn.CrossEntropyLoss()

### 优化器

优化器的任务是调整神经网络权重，从而让损失函数的值不断减小。

PyTorch 在 `torch.optim` 模块中内置了[多种优化算法](https://pytorch.org/docs/stable/optim.html)。

其中两种最常用的优化器包括：
* [`torch.optim.SGD(lr=0.1, params=model.parameters())`](https://pytorch.org/docs/stable/generated/torch.optim.SGD.html#torch.optim.SGD) - SGD 即[随机梯度下降](https://en.wikipedia.org/wiki/Stochastic_gradient_descent)（`lr` 表示学习率，决定每一步更新权重的幅度，值小则调整更细，值大则调整更快）。
* [`torch.optim.Adam(lr=0.001, params=model.parameters())`](https://pytorch.org/docs/stable/generated/torch.optim.Adam.html#torch.optim.Adam) - Adam 优化器（`params` 表示模型参数，也就是训练过程中需要被优化的权重参数）。

In [32]:
# 创建基线模型
model = nn.Transformer()

# SGD（随机梯度下降）
optimizer = torch.optim.SGD(lr=0.1, # set the learning rate (required)
                            params=model.parameters()) # tell the optimizer what parameters to optimize

In [33]:
# 创建基线模型
model = nn.Transformer()

# Adam 优化器
optimizer = torch.optim.Adam(lr=0.001, # set the learning rate (required)
                             params=model.parameters()) # tell the optimizer what parameters to optimize

## 端到端示例工作流

下面把前面的内容快速串起来，看一个端到端流程示例。

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/01_a_pytorch_workflow.png" width=950 alt="从数据到建模、训练再到评估的 PyTorch 工作流"/> 

该流程来源于 [01. PyTorch Workflow Fundamentals](https://www.learnpytorch.io/01_pytorch_workflow/)。

### Create data

In [34]:
# 创建“已知”参数
weight = 0.7
bias = 0.3

# 创建数据
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1) # data
y = weight * X + bias # labels (want model to learn from data to predict these)

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [35]:
# 创建训练/测试划分
train_split = int(0.8 * len(X)) # 80% of data used for training set, 20% for testing 
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

### 创建模型

在 PyTorch 中创建模型有两种主要方式：
1. 继承 `torch.nn.Module` - 代码更多，但灵活性更强；所有继承 `torch.nn.Module` 的模型都必须实现 `forward()` 方法。
2. 使用 `torch.nn.Sequential` - 代码更少，但灵活性相对较低。

In [36]:
from torch import nn

# 方式 1：继承 torch.nn.Module
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        # 使用 nn.Linear() 创建模型参数
        self.linear_layer = nn.Linear(in_features=1, 
                                      out_features=1)
    
    # 定义前向计算（输入数据 x 流经 nn.Linear()）
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

model_0 = LinearRegressionModel()
model_0, model_0.state_dict()

(LinearRegressionModel(
   (linear_layer): Linear(in_features=1, out_features=1, bias=True)
 ),
 OrderedDict([('linear_layer.weight', tensor([[0.5025]])),
              ('linear_layer.bias', tensor([-0.0722]))]))

下面我们使用 `torch.nn.Sequential` 创建一个与上面相同的模型。

In [37]:
from torch import nn

# 方式 2：使用 torch.nn.Sequential
model_1 = torch.nn.Sequential(
    nn.Linear(in_features=1,
              out_features=1))

model_1, model_1.state_dict()

(Sequential(
   (0): Linear(in_features=1, out_features=1, bias=True)
 ),
 OrderedDict([('0.weight', tensor([[0.9905]])), ('0.bias', tensor([0.9053]))]))

### 配置损失函数与优化器

In [38]:
# 创建损失函数
loss_fn = nn.L1Loss()

# 创建优化器
optimizer = torch.optim.SGD(params=model_1.parameters(), # optimize newly created model's parameters
                            lr=0.01)

### 创建训练/测试循环

我们的目标是降低模型损失（也就是模型预测与真实数据之间的差距）。

如果训练/测试循环实现正确，且模型确实能从数据中学习到模式，那么训练损失和测试损失都应该逐步下降。

关于 PyTorch 训练循环，可参考以下资源：
* [PyTorch 优化循环歌曲](https://youtu.be/Nutpusq_AFw)
* [PyTorch 工作流基础 第 3 节：训练循环](https://www.learnpytorch.io/01_pytorch_workflow/#pytorch-training-loop)
* [PyTorch 工作流基础 第 3 节：测试循环](https://www.learnpytorch.io/01_pytorch_workflow/#pytorch-testing-loop)
* [PyTorch 工作流基础 第 6.3 节：训练](https://www.learnpytorch.io/01_pytorch_workflow/#63-training)

In [40]:
torch.manual_seed(42)

# 设置训练轮数
epochs = 1000 

# 将数据放到可用设备上
# 若不这样做会报错（并非所有数据都在目标设备上）
X_train = X_train.to(device)
X_test = X_test.to(device)
y_train = y_train.to(device)
y_test = y_test.to(device)

# 将模型放到可用设备上
# 若不这样做会报错（模型不在目标设备上）
model_1 = model_1.to(device)

for epoch in range(epochs):
    ### Training
    model_1.train() # train mode is on by default after construction

    # 1. Forward pass
    y_pred = model_1(X_train)

    # 2. Calculate loss
    loss = loss_fn(y_pred, y_train)

    # 3. Zero grad optimizer
    optimizer.zero_grad()

    # 4. Loss backward
    loss.backward()

    # 5. Step the optimizer
    optimizer.step()

    ### Testing
    model_1.eval() # put the model in evaluation mode for testing (inference)
    # 1. Forward pass
    with torch.inference_mode():
        test_pred = model_1(X_test)
    
        # 2. Calculate the loss
        test_loss = loss_fn(test_pred, y_test)

    if epoch % 100 == 0:
        print(f"Epoch: {epoch} | Train loss: {loss} | Test loss: {test_loss}")

Epoch: 0 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 100 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 200 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 300 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 400 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 500 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 600 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 700 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 800 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263
Epoch: 900 | Train loss: 0.008362661115825176 | Test loss: 0.005596190690994263


## 扩展资源

上面的清单并不穷尽全部内容。

如果你想继续深入，可以参考以下资源：

* [PyTorch 官方速查表](https://pytorch.org/tutorials/beginner/ptcheat.html)。
* [Zero to Mastery Learn PyTorch course](https://dbourke.link/ZTMPyTorch) - 一门兼顾系统性与入门友好的综合课程，从基础一直到模型部署到真实场景供他人使用。
* [PyTorch performance tuning guide](https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html) - PyTorch 官方团队提供的性能调优指南。
* [PyTorch Extra Resources](https://www.learnpytorch.io/pytorch_extra_resources/) - 精选扩展资源列表，帮助你学习 PyTorch 与深度学习工程化相关内容。
* [Effective PyTorch by vahidk](https://github.com/vahidk/EffectivePyTorch) - 一个很棒的 GitHub 仓库，用直观方式梳理了 PyTorch 的核心功能。